version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "go-fork/maintainers"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "go-fork/maintainers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    assignees:
      - "go-fork/devops-team"
    labels:
      - "dependencies"
      - "github_actions"
    commit-message:
      prefix: "ci"
      include: "scope"
