# Các nền tảng tài trợ cho go.fork.vn/di
github: [go-fork]
patreon: gofork
open_collective: gofork
ko_fi: gofork
liberapay: gofork
custom: ["https://www.paypal.me/gofork", "https://gofork.dev/donate"]
