with-expecter: true
resolve-type-alias: false
disable-version-string: true
quiet: false
dir: "mocks"  # Giữ nguyên tên thư mục mocks
outpkg: "{{.PackageName}}_mocks"  # Đặt tên package động theo tên package gốc
mockname: "Mock{{.InterfaceName}}"  # Chuẩn đặt tên mock
structname: "Mock{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.go"  # Tên file mock theo tên interface
issue-845-fix: true
recursive: true
packages:
  go.fork.vn/di:
    interfaces:
      Application:
      Container:
      ServiceProvider:
      ServiceProviderDeferred:
      ModuleLoaderContract:
all: false
