with-expecter: true
dir: mocks
outpkg: mocks
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  go.fork.vn/di:
    interfaces:
      Application:
        config:
          recursive: true
      Container:
        config:
          recursive: true
      ServiceProvider:
        config:
          recursive: true
      ServiceProviderDeferred:
        config:
          recursive: true
      ModuleLoaderContract:
        config:
          recursive: true
all: false
