name: Bug report
description: Tạo báo cáo lỗi để giúp chúng tôi cải thiện go-fork/di
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã dành thời gian để báo cáo lỗi!
  - type: textarea
    id: description
    attributes:
      label: Mô tả lỗi
      description: Mô tả rõ ràng và ngắn gọn về lỗi là gì.
      placeholder: Khi tôi sử dụng phương thức X với tham số Y, tôi gặp lỗi Z thay vì kết quả mong đợi là W.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Các bước tái hiện
      description: Các bước để tái hiện lỗi
      placeholder: |
        1. Sử dụng phương thức '...'
        2. Truyền tham số '...'
        3. Nhận lỗi '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Hành vi mong đợi
      description: Mô tả rõ ràng và ngắn gọn về những gì bạn mong đợi sẽ xảy ra.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Mã tái hiện
      description: Cung cấp mã tái hiện nếu có thể
      render: go
  - type: input
    id: version
    attributes:
      label: Phiên bản
      description: Phiên bản go-fork/di bạn đang sử dụng
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Phiên bản Go
      description: Phiên bản Go bạn đang sử dụng
      placeholder: go1.23.9
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Thông tin bổ sung
      description: Thêm bất kỳ thông tin bổ sung nào về vấn đề ở đây.
