// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	di "go.fork.vn/di"
)

// ServiceProviderDeferred is an autogenerated mock type for the ServiceProviderDeferred type
type ServiceProviderDeferred struct {
	mock.Mock
}

// Boot provides a mock function with given fields: app
func (_m *ServiceProviderDeferred) Boot(app di.Application) {
	_m.Called(app)
}

// DeferredBoot provides a mock function with given fields: app
func (_m *ServiceProviderDeferred) DeferredBoot(app di.Application) {
	_m.Called(app)
}

// Providers provides a mock function with no fields
func (_m *ServiceProviderDeferred) Providers() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Providers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Register provides a mock function with given fields: app
func (_m *ServiceProviderDeferred) Register(app di.Application) {
	_m.Called(app)
}

// Requires provides a mock function with no fields
func (_m *ServiceProviderDeferred) Requires() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Requires")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewServiceProviderDeferred creates a new instance of ServiceProviderDeferred. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProviderDeferred(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProviderDeferred {
	mock := &ServiceProviderDeferred{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
