// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceProviderDeferred is an autogenerated mock type for the ServiceProviderDeferred type
type ServiceProviderDeferred struct {
	mock.Mock
}

// Boot provides a mock function with given fields: app
func (_m *ServiceProviderDeferred) Boot(app interface{}) {
	_m.Called(app)
}

// DeferredBoot provides a mock function with given fields: app
func (_m *ServiceProviderDeferred) DeferredBoot(app interface{}) {
	_m.Called(app)
}

// Register provides a mock function with given fields: app
func (_m *ServiceProviderDeferred) Register(app interface{}) {
	_m.Called(app)
}

// NewServiceProviderDeferred creates a new instance of ServiceProviderDeferred. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProviderDeferred(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProviderDeferred {
	mock := &ServiceProviderDeferred{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
