name: Auto Update Dependencies

on:
  schedule:
    # Run every Monday at 8:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    name: Update Go Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: Update dependencies
        run: |
          go get -u all
          go mod tidy
          go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Go dependencies"
          title: "chore: update Go dependencies"
          body: |
            This PR updates all Go dependencies to their latest versions.
            
            Changes:
            - Updated all Go module dependencies
            - Ran `go mod tidy` to clean up
            - Verified all tests still pass
            
            Auto-generated by GitHub Actions.
          branch: chore/update-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated
          assignees: |
            ${{ github.actor }}
